name: scala format check ci
run-name: ${{ github.actor }} run scala format check ci

on:
  push:
    branches: 
      - "master"
      - "pavel/**"
      - "develop"
      - "vasiliy/**"
      - "ilsaf_k/**"
      - "andrey/**"
      - "vlad_v/**"
      - "kirill_s/**"
      - "artem_s/**"
      - "alex_r/**"
      - "nikt/**"
      - "shustikov/**"
      - "vindyukov/**"
    paths:
      - 'consolidation/stg_loader/**'
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: consolidation/stg_loader

jobs:
 format:
    runs-on: [self-hosted, dwh]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Scalafmt check
      run: |
        scala-cli fmt --check ./src/main/scala || (
          echo "To format code run"
          echo "  scala-cli fmt ."
          exit 1
        )