name: Migrate Secrets
run-name: ${{ github.actor }} run migrate vault secrets
on:
  workflow_dispatch:
    inputs:
      target_point:
        description: "Укажи целевую точку монтирования"
        type: string
        required: true

jobs:
  migrate-secrets:
    runs-on: [self-hosted, dwh]
    environment: dev
    env:
      VAULT_ADDRESS: ${{ vars.VAULT_ADDRESS }}
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip dependencies
        run: python3.11 -m pip install -r deploy/workflows/requirements.txt

      - name: Run migration script
        run: python3.11 dwh_tool/lib/vault_migration.py --target-point ${{ inputs.target_point }}
