name: workflow app docker image ci
run-name: ${{ github.actor }} run workflow app = "${{ inputs.app }}" docker image ci

on:
  workflow_call:
    inputs:
      app:
        description: 'App to deploy'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy'
        required: true
        type: string

env:
  APPS_DIR: workflow_apps

jobs:
  build-and-publish:
    runs-on: [self-hosted, dwh]
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Harbor Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_LOGIN }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./${{ env.APPS_DIR }}/${{ inputs.app }}/docker/Dockerfile
        push: true
        tags: ${{ secrets.HARBOR_REGISTRY }}/dwh_prod/teams/workflows_app__${{ inputs.app }}:latest
